#!/bin/bash
#PBS -V
#PBS -l mppwidth=24
#PBS -l mppdepth=1
#PBS -l walltime=0:30:00
#PBS -o testing_c2.stdout
#PBS -j oe
#PBS -A mp309

cd $PBS_O_WORKDIR

TIME=times_c2.txt

# 2500 10000 22500 40000 62500 90000 122500 160000 202500 250000

for P in 8; do
	for N in 202500; do
		aprun -d 1 -n $P -N $P ../implementations/bin/mpi-ca-all-pairs -i ../test_cases/n$N/test_data.txt -t ${TIME} -c 2
	done
done
