#!/bin/bash
#PBS -V
#PBS -l mppwidth=24
#PBS -l mppdepth=1
#PBS -l walltime=0:30:00
#PBS -o testing_c1.stdout
#PBS -j oe
#PBS -A mp309

cd $PBS_O_WORKDIR

TIME=times_c1.txt

for P in 1 2 4 16 24; do
	for N in 202500 250000; do
		aprun -d 1 -n $P -N $P ../implementations/bin/mpi-ca-all-pairs -i ../test_cases/n$N/test_data.txt -t ${TIME}
	done
done
